### ISSUE TITLE
Help with build

### ISSUE THREAD

**Issue by robert7** [d1vanov/QEverCloud-example-NotePoster#1]
Hi Dmitry, 
I would need a bit help with building of the project.. 
My knowledge of cmake is ... very very limited ..

Could you provide a little bit info, how should I setup the environment, that compiler finds QEvercloud?
(I would like to update Nixnote from QEvercloud 4 to 5.1 ... as I have difficulties with v.4. But I don't understand the changes in NoteStore/UserStore.. so working example would be helpful).
I can't find the requested "cmake" files.. (see image)
thanks
Robert 

![image](https://user-images.githubusercontent.com/1135218/77058628-fe159800-69d5-11ea-8911-42c22a048235.png)

**Comment by d1vanov** [comment]
Hi, you should add `-DQEverCloud-qt5_DIR=<path-to-QEverCloud-installation-prefix>/lib/cmake/QEverCloud-qt5` to your `CMake` command.

**Comment by d1vanov** [comment]
Actually, this repository won't help your case as I forgot to update it after QEverCloud 5.1 release. I should do it.

**Comment by d1vanov** [comment]
Pushed quick and dirty adaptation to QEverCloud 5.1

**Comment by robert7** [comment]
thanks! I will try it

**Comment by robert7** [comment]
Sorry there is still something wrong..
I did a build of QEvercloud in `~/Projects/QEverCloud/build` by `cmake ..`
Then the directory I need to set `QEverCloud-qt5_DIR` to is
`~/Projects/QEverCloud/build/QEverCloud/CMakeFiles/Export/lib/cmake/QEverCloud-qt5` correct?

Then I set `-DQEverCloud-qt5_DIR=~/Projects/QEverCloud/build/QEverCloud/CMakeFiles/Export/lib/cmake/QEverCloud-qt5` correct?

![image](https://user-images.githubusercontent.com/1135218/77095554-5c5e6d00-6a0e-11ea-8c6b-3dfda0322171.png)

`QEverCloud-qt5Config.cmake`is only found in `~/Projects/QEverCloud/build` but setting `QEverCloud-qt5_DIR` to `~/Projects/QEverCloud/build` did not worked either ..

**Comment by d1vanov** [comment]
You need to install `QEverCloud`, only building is not enough. For this you can do e.g. `cd build && cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/installdir .. && make && make install`. Then for note poster you do `cmake -DQEverCloud-qt5_DIR=<path-to-QEverCloud-repo>/build/installdir/lib/cmake/QEverCloud-qt5`.

**Comment by robert7** [comment]
It works now. Thank you.
Sorry for stupid questions, as I said my knowledge od C++ and its build system is very limited. because of very limited time, I either need to use some shortcuts or forget it at all.
